### ISSUE TITLE
Support-android out of date

### ISSUE THREAD

**Issue by xkmato** [rapidpro/ureport-android#1]
Can't build the project. `Error:(16, 36) error: cannot find symbol class DateFormatter` in `app/src/main/java/in/ureport/views/adapters/ContributionAdapter.java`

I am wondering where I can find an up to date version of support-android

**Comment by johncordeiro** [comment]
You can find it here: https://github.com/Ilhasoft/support-android
I will add the module soon.

**Comment by xkmato** [comment]
yes I have checked that out already but it is not up to date. The class `br.com.ilhasoft.support.tool.DateFormatter` is missing and methods `setDateFormat` and `get` are missing on `JsonDeserializer`

It seems like it does not get updated at the same time with this repo

**Comment by johncordeiro** [comment]
Please check now.

**Comment by xkmato** [comment]
thank you
